//hot nonsense generated by copilot, not used in final product
// import React, { useState, useMemo } from "react";

// export default function KalshiCard({
//     title = "Will XYZ close above $100 on 2026-12-31?",
//     price = 64.2, // price as percent (e.g., 64.2 means $0.642 for a $1 payout)
//     onPlaceBet = (bet) => console.log("place bet", bet),
// }) {
//     const [side, setSide] = useState("YES"); // "YES" or "NO"
//     const [stake, setStake] = useState(""); // dollars to spend

//     const priceForSide = useMemo(() => {
//         return side === "YES" ? price : 100 - price;
//     }, [side, price]);

//     const parsedStake = parseFloat(stake);
//     const validStake = !Number.isNaN(parsedStake) && parsedStake > 0;

//     // Contracts you buy for given stake: contracts = stake / (price/100)
//     const contracts = validStake && priceForSide > 0
//         ? parsedStake / (priceForSide / 100)
//         : 0;

//     // Payout if the side resolves true: contracts * $1
//     const potentialPayout = contracts;

//     function handlePlace() {
//         if (!validStake) return;
//         onPlaceBet({
//             side,
//             stake: parsedStake,
//             price: priceForSide,
//             contracts,
//             potentialPayout,
//             timestamp: Date.now(),
//         });
//     }

//     const priceColor = price >= 50 ? "#137f24" : "#b91c1c";

//     const styles = {
//         card: {
//             maxWidth: 420,
//             border: "1px solid #e6e6e6",
//             borderRadius: 10,
//             padding: 16,
//             fontFamily: "Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial",
//             background: "#fff",
//             boxShadow: "0 2px 8px rgba(12, 18, 26, .06)",
//         },
//         header: { display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: 12 },
//         title: { fontSize: 16, fontWeight: 600, color: "#0f172a" },
//         price: { fontSize: 18, fontWeight: 700, color: priceColor },
//         body: { display: "grid", gap: 10 },
//         sides: { display: "flex", gap: 8 },
//         sideBtn: (active, color) => ({
//             flex: 1,
//             padding: "8px 10px",
//             borderRadius: 8,
//             border: active ? `1px solid ${color}` : "1px solid #e6e6e6",
//             background: active ? `${color}10` : "#fff",
//             cursor: "pointer",
//             textAlign: "center",
//             fontWeight: 600,
//             color: active ? color : "#0f172a",
//         }),
//         inputRow: { display: "flex", gap: 8, alignItems: "center" },
//         input: { flex: 1, padding: 8, borderRadius: 8, border: "1px solid #e6e6e6" },
//         info: { display: "flex", justifyContent: "space-between", fontSize: 13, color: "#334155" },
//         placeBtn: { marginTop: 8, width: "100%", padding: "10px 12px", borderRadius: 8, border: "none", background: "#0ea5e9", color: "#fff", fontWeight: 700, cursor: "pointer" },
//         smallMuted: { fontSize: 12, color: "#64748b" },
//     };

//     return (
//         <div style={styles.card}>
//             <div style={styles.header}>
//                 <div style={styles.title}>{title}</div>
//                 <div style={styles.price}>{price.toFixed(2)}%</div>
//             </div>

//             <div style={styles.body}>
//                 <div style={styles.sides}>
//                     <button
//                         type="button"
//                         onClick={() => setSide("YES")}
//                         style={styles.sideBtn(side === "YES", "#059669")}
//                         aria-pressed={side === "YES"}
//                     >
//                         YES
//                     </button>
//                     <button
//                         type="button"
//                         onClick={() => setSide("NO")}
//                         style={styles.sideBtn(side === "NO", "#ef4444")}
//                         aria-pressed={side === "NO"}
//                     >
//                         NO
//                     </button>
//                 </div>

//                 <div style={styles.inputRow}>
//                     <input
//                         style={styles.input}
//                         inputMode="decimal"
//                         placeholder="Amount to spend (USD)"
//                         value={stake}
//                         onChange={(e) => setStake(e.target.value)}
//                     />
//                     <div style={{ minWidth: 92, textAlign: "right", fontWeight: 600 }}>
//                         {priceForSide.toFixed(2)}%
//                     </div>
//                 </div>

//                 <div style={styles.info}>
//                     <div>
//                         <div style={styles.smallMuted}>Estimated contracts</div>
//                         <div>{validStake ? contracts.toFixed(4) : "—"}</div>
//                     </div>
//                     <div>
//                         <div style={styles.smallMuted}>Potential payout</div>
//                         <div>${validStake ? potentialPayout.toFixed(2) : "—"}</div>
//                     </div>
//                 </div>

//                 <button
//                     type="button"
//                     onClick={handlePlace}
//                     style={styles.placeBtn}
//                     disabled={!validStake}
//                 >
//                     Place {side} Bet
//                 </button>
//             </div>
//         </div>
//     );
// }

/**
 * KalshiCard.jsx
 *
 * Props — market object:
 *   title       string   — the market question
 *   closeDate   string   — human-readable close date e.g. "May 7, 2025"
 *   category    string   — e.g. "Politics & Macro"
 *   yesPrice    number   — cents, 0–100
 *   noPrice     number   — cents, 0–100
 *   volume      string   — formatted volume e.g. "$1.4M"
 *   marketUrl   string   — link to the Kalshi market page
 */

export default function KalshiCard({ market }) {
  const { title, closeDate, category, yesPrice, noPrice, volume, marketUrl } = market;

  const yesWidth = `${yesPrice}%`;

  const handleBet = () => {
    if (marketUrl) window.open(marketUrl, "_blank", "noopener,noreferrer");
  };

  return (
    <div style={{
      background: "var(--color-background-primary)",
      border: "0.5px solid var(--color-border-tertiary)",
      borderRadius: "var(--border-radius-lg)",
      padding: "1rem 1.25rem",
      transition: "border-color 0.15s",
    }}
      onMouseEnter={e => e.currentTarget.style.borderColor = "var(--color-border-secondary)"}
      onMouseLeave={e => e.currentTarget.style.borderColor = "var(--color-border-tertiary)"}
    >

      {/* Tag */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 10 }}>
        <span style={{
          fontSize: 11, fontWeight: 500, padding: "2px 8px",
          borderRadius: "var(--border-radius-md)",
          background: "#E6F1FB", color: "#0C447C",
        }}>
          Kalshi
        </span>
        <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>
          {category}
        </span>
      </div>

      {/* Title */}
      <div style={{
        fontSize: 15, fontWeight: 500,
        color: "var(--color-text-primary)",
        lineHeight: 1.4, marginBottom: 6,
      }}>
        {title}
      </div>

      {/* Close date */}
      <div style={{ fontSize: 12, color: "var(--color-text-tertiary)", marginBottom: 14 }}>
        Closes {closeDate}
      </div>

      {/* Yes/No price pills */}
      <div style={{ display: "flex", gap: 10, marginBottom: 12 }}>
        <div style={{
          flex: 1, padding: "8px 12px",
          borderRadius: "var(--border-radius-md)",
          border: "0.5px solid var(--color-border-tertiary)",
          textAlign: "center",
        }}>
          <div style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginBottom: 2 }}>Yes</div>
          <div style={{ fontSize: 17, fontWeight: 500, color: "#1D9E75" }}>{yesPrice}¢</div>
        </div>
        <div style={{
          flex: 1, padding: "8px 12px",
          borderRadius: "var(--border-radius-md)",
          border: "0.5px solid var(--color-border-tertiary)",
          textAlign: "center",
        }}>
          <div style={{ fontSize: 11, color: "var(--color-text-tertiary)", marginBottom: 2 }}>No</div>
          <div style={{ fontSize: 17, fontWeight: 500, color: "#D85A30" }}>{noPrice}¢</div>
        </div>
      </div>

      {/* Probability bar */}
      <div style={{
        height: 4, borderRadius: 999,
        background: "var(--color-background-secondary)",
        marginBottom: 14, overflow: "hidden",
      }}>
        <div style={{
          height: "100%", width: yesWidth,
          background: "#1D9E75",
          borderRadius: 999,
          transition: "width 0.4s ease",
        }} />
      </div>

      {/* Footer — volume + bet button */}
      <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
        <span style={{ fontSize: 12, color: "var(--color-text-tertiary)" }}>
          Vol: {volume}
        </span>
        <button
          onClick={handleBet}
          style={{
            fontSize: 13, padding: "6px 18px",
            borderRadius: "var(--border-radius-md)",
            border: "0.5px solid var(--color-border-secondary)",
            background: "transparent",
            color: "var(--color-text-primary)",
            cursor: "pointer",
            fontFamily: "var(--font-sans)",
            transition: "background 0.15s",
          }}
          onMouseEnter={e => e.currentTarget.style.background = "var(--color-background-secondary)"}
          onMouseLeave={e => e.currentTarget.style.background = "transparent"}
        >
          Bet →
        </button>
      </div>

    </div>
  );
}